





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace LaunchContent.LaunchSitecore.Base_Templates
{


    /// <summary>
    /// IGeneral_Fields Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Base Templates/General Fields</para>
    /// <para>ID: 2bc9e276-d594-4d97-9cf3-b229c52a6d1f</para>
    /// </summary>
    [SitecoreType(TemplateId=IGeneral_FieldsConstants.TemplateIdString)]
    public partial interface IGeneral_Fields : IGlassBase 
    {
                                /// <summary>
                    /// The Icon field.
                    /// <para></para>
                    /// <para>Field Type: Image</para>
                    /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IGeneral_FieldsConstants.IconFieldName)]
                    Image Icon  {get; set;}
            
                }


    public static partial class IGeneral_FieldsConstants{

            public const string TemplateIdString = "2bc9e276-d594-4d97-9cf3-b229c52a6d1f";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "General Fields";

                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
        
    }

    /// <summary>
    /// General_Fields
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Base Templates/General Fields</para>
    /// <para>ID: 2bc9e276-d594-4d97-9cf3-b229c52a6d1f</para>
    /// </summary>
    [SitecoreType(TemplateId=IGeneral_FieldsConstants.TemplateIdString)]
    public partial class General_Fields  : GlassBase, IGeneral_Fields 
    {
       
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGeneral_FieldsConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore.Base_Templates
{


    /// <summary>
    /// ITitle_Abstract_And_Text Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Base Templates/Title Abstract and Text</para>
    /// <para>ID: 2bdc8af6-c00e-44a9-a644-4946a252a02e</para>
    /// </summary>
    [SitecoreType(TemplateId=ITitle_Abstract_And_TextConstants.TemplateIdString)]
    public partial interface ITitle_Abstract_And_Text : IGlassBase 
    {
                                /// <summary>
                    /// The Abstract field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>
                    /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITitle_Abstract_And_TextConstants.AbstractFieldName)]
                    string Abstract  {get; set;}
            
                                /// <summary>
                    /// The Body field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>
                    /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITitle_Abstract_And_TextConstants.BodyFieldName)]
                    string Body  {get; set;}
            
                                /// <summary>
                    /// The Title field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITitle_Abstract_And_TextConstants.TitleFieldName)]
                    string Title  {get; set;}
            
                }


    public static partial class ITitle_Abstract_And_TextConstants{

            public const string TemplateIdString = "2bdc8af6-c00e-44a9-a644-4946a252a02e";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Title Abstract and Text";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
        
    }

    /// <summary>
    /// Title_Abstract_And_Text
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Base Templates/Title Abstract and Text</para>
    /// <para>ID: 2bdc8af6-c00e-44a9-a644-4946a252a02e</para>
    /// </summary>
    [SitecoreType(TemplateId=ITitle_Abstract_And_TextConstants.TemplateIdString)]
    public partial class Title_Abstract_And_Text  : GlassBase, ITitle_Abstract_And_Text 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITitle_Abstract_And_TextConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITitle_Abstract_And_TextConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITitle_Abstract_And_TextConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore.Base_Templates
{


    /// <summary>
    /// ISite_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Base Templates/Site Section</para>
    /// <para>ID: d24c6488-4a2b-4de4-b033-ef3072aea6f3</para>
    /// </summary>
    [SitecoreType(TemplateId=ISite_SectionConstants.TemplateIdString)]
    public partial interface ISite_Section : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text, global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                                /// <summary>
                    /// The Image field.
                    /// <para></para>
                    /// <para>Field Type: Image</para>
                    /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ISite_SectionConstants.ImageFieldName)]
                    Image Image  {get; set;}
            
                }


    public static partial class ISite_SectionConstants{

            public const string TemplateIdString = "d24c6488-4a2b-4de4-b033-ef3072aea6f3";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Site Section";

                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
        
    }

    /// <summary>
    /// Site_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Base Templates/Site Section</para>
    /// <para>ID: d24c6488-4a2b-4de4-b033-ef3072aea6f3</para>
    /// </summary>
    [SitecoreType(TemplateId=ISite_SectionConstants.TemplateIdString)]
    public partial class Site_Section  : GlassBase, ISite_Section 
    {
       
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISite_SectionConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISite_SectionConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISite_SectionConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISite_SectionConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISite_SectionConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
            }
}
