





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace LaunchContent
{

    public partial interface IGlassBase{
        
        [SitecoreId]
        Guid Id{ get; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

    }

    public abstract partial class GlassBase : IGlassBase{
        
        [SitecoreId]
        public virtual Guid Id{ get; private set;}

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
    }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IHome Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Home</para>
    /// <para>ID: 0acd30d8-863e-4b1d-8612-719eefc1da4f</para>
    /// </summary>
    [SitecoreType(TemplateId=IHomeConstants.TemplateIdString)]
    public partial interface IHome : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                                /// <summary>
                    /// The Body field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>
                    /// <para>Field ID: 764646d1-347e-419d-8b86-67457c73d905</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeConstants.BodyFieldName)]
                    string Body  {get; set;}
            
                                /// <summary>
                    /// The Call to Action Link field.
                    /// <para></para>
                    /// <para>Field Type: Droptree</para>
                    /// <para>Field ID: 918a64f3-3ce1-46fe-afe0-7bdeae9f6299</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeConstants.Call_To_Action_LinkFieldName)]
                    Guid Call_To_Action_Link  {get; set;}
            
                                /// <summary>
                    /// The Call to Action Text field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: 4b8cff92-abb0-4d0a-a396-cd2ad4b5a99b</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeConstants.Call_To_Action_TextFieldName)]
                    string Call_To_Action_Text  {get; set;}
            
                                /// <summary>
                    /// The Subtitle field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: 2fb9aebd-d6e1-4ea5-8a04-7b6ad0ec3132</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeConstants.SubtitleFieldName)]
                    string Subtitle  {get; set;}
            
                                /// <summary>
                    /// The Title field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: aaeac7f2-e33e-4b34-9023-ab6f59d3a427</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeConstants.TitleFieldName)]
                    string Title  {get; set;}
            
                }


    public static partial class IHomeConstants{

            public const string TemplateIdString = "0acd30d8-863e-4b1d-8612-719eefc1da4f";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Home";

                    
            public static readonly ID BodyFieldId = new ID("764646d1-347e-419d-8b86-67457c73d905");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID Call_To_Action_LinkFieldId = new ID("918a64f3-3ce1-46fe-afe0-7bdeae9f6299");
            public const string Call_To_Action_LinkFieldName = "Call to Action Link";
            
                    
            public static readonly ID Call_To_Action_TextFieldId = new ID("4b8cff92-abb0-4d0a-a396-cd2ad4b5a99b");
            public const string Call_To_Action_TextFieldName = "Call to Action Text";
            
                    
            public static readonly ID SubtitleFieldId = new ID("2fb9aebd-d6e1-4ea5-8a04-7b6ad0ec3132");
            public const string SubtitleFieldName = "Subtitle";
            
                    
            public static readonly ID TitleFieldId = new ID("aaeac7f2-e33e-4b34-9023-ab6f59d3a427");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Home
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Home</para>
    /// <para>ID: 0acd30d8-863e-4b1d-8612-719eefc1da4f</para>
    /// </summary>
    [SitecoreType(TemplateId=IHomeConstants.TemplateIdString)]
    public partial class Home  : GlassBase, IHome 
    {
       
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 764646d1-347e-419d-8b86-67457c73d905</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Call to Action Link field.
                /// <para></para>
                /// <para>Field Type: Droptree</para>
                /// <para>Field ID: 918a64f3-3ce1-46fe-afe0-7bdeae9f6299</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.Call_To_Action_LinkFieldName)]
                public virtual Guid Call_To_Action_Link  {get; set;}
                    
                        /// <summary>
                /// The Call to Action Text field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 4b8cff92-abb0-4d0a-a396-cd2ad4b5a99b</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.Call_To_Action_TextFieldName)]
                public virtual string Call_To_Action_Text  {get; set;}
                    
                        /// <summary>
                /// The Subtitle field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 2fb9aebd-d6e1-4ea5-8a04-7b6ad0ec3132</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.SubtitleFieldName)]
                public virtual string Subtitle  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: aaeac7f2-e33e-4b34-9023-ab6f59d3a427</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IHomeConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IArticle_Group Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Article Group</para>
    /// <para>ID: 1b6a3702-5694-4fc4-8366-989ecdcd7f1b</para>
    /// </summary>
    [SitecoreType(TemplateId=IArticle_GroupConstants.TemplateIdString)]
    public partial interface IArticle_Group : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ISite_Section
    {
                }


    public static partial class IArticle_GroupConstants{

            public const string TemplateIdString = "1b6a3702-5694-4fc4-8366-989ecdcd7f1b";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Article Group";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Article_Group
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Article Group</para>
    /// <para>ID: 1b6a3702-5694-4fc4-8366-989ecdcd7f1b</para>
    /// </summary>
    [SitecoreType(TemplateId=IArticle_GroupConstants.TemplateIdString)]
    public partial class Article_Group  : GlassBase, IArticle_Group 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticle_GroupConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticle_GroupConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticle_GroupConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticle_GroupConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticle_GroupConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IError_Page Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Error Page</para>
    /// <para>ID: 455b0cd7-43ee-4553-a7ad-fffc1da2143e</para>
    /// </summary>
    [SitecoreType(TemplateId=IError_PageConstants.TemplateIdString)]
    public partial interface IError_Page : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ISite_Section
    {
                }


    public static partial class IError_PageConstants{

            public const string TemplateIdString = "455b0cd7-43ee-4553-a7ad-fffc1da2143e";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Error Page";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Error_Page
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Error Page</para>
    /// <para>ID: 455b0cd7-43ee-4553-a7ad-fffc1da2143e</para>
    /// </summary>
    [SitecoreType(TemplateId=IError_PageConstants.TemplateIdString)]
    public partial class Error_Page  : GlassBase, IError_Page 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IError_PageConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IError_PageConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IError_PageConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IError_PageConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IError_PageConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore.Site_Sections
{


    /// <summary>
    /// IArticles_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Articles Section</para>
    /// <para>ID: 53303aa5-8e78-4263-a476-c1e7ed791fde</para>
    /// </summary>
    [SitecoreType(TemplateId=IArticles_SectionConstants.TemplateIdString)]
    public partial interface IArticles_Section : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ISite_Section
    {
                }


    public static partial class IArticles_SectionConstants{

            public const string TemplateIdString = "53303aa5-8e78-4263-a476-c1e7ed791fde";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Articles Section";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Articles_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Articles Section</para>
    /// <para>ID: 53303aa5-8e78-4263-a476-c1e7ed791fde</para>
    /// </summary>
    [SitecoreType(TemplateId=IArticles_SectionConstants.TemplateIdString)]
    public partial class Articles_Section  : GlassBase, IArticles_Section 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticles_SectionConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticles_SectionConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticles_SectionConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticles_SectionConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticles_SectionConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore.Site_Sections
{


    /// <summary>
    /// ITeam_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Team Section</para>
    /// <para>ID: 6e005e97-5435-4806-98e5-ca454b8218d1</para>
    /// </summary>
    [SitecoreType(TemplateId=ITeam_SectionConstants.TemplateIdString)]
    public partial interface ITeam_Section : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ISite_Section
    {
                }


    public static partial class ITeam_SectionConstants{

            public const string TemplateIdString = "6e005e97-5435-4806-98e5-ca454b8218d1";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Team Section";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Team_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Team Section</para>
    /// <para>ID: 6e005e97-5435-4806-98e5-ca454b8218d1</para>
    /// </summary>
    [SitecoreType(TemplateId=ITeam_SectionConstants.TemplateIdString)]
    public partial class Team_Section  : GlassBase, ITeam_Section 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_SectionConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_SectionConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_SectionConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_SectionConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_SectionConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IMicrosite_Home Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Microsite Home</para>
    /// <para>ID: 7139a8b6-68d9-471f-96e4-b87ed703c185</para>
    /// </summary>
    [SitecoreType(TemplateId=IMicrosite_HomeConstants.TemplateIdString)]
    public partial interface IMicrosite_Home : IGlassBase , global::LaunchContent.LaunchSitecore.IHome
    {
                }


    public static partial class IMicrosite_HomeConstants{

            public const string TemplateIdString = "7139a8b6-68d9-471f-96e4-b87ed703c185";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Microsite Home";

                    
            public static readonly ID BodyFieldId = new ID("764646d1-347e-419d-8b86-67457c73d905");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID Call_To_Action_LinkFieldId = new ID("918a64f3-3ce1-46fe-afe0-7bdeae9f6299");
            public const string Call_To_Action_LinkFieldName = "Call to Action Link";
            
                    
            public static readonly ID Call_To_Action_TextFieldId = new ID("4b8cff92-abb0-4d0a-a396-cd2ad4b5a99b");
            public const string Call_To_Action_TextFieldName = "Call to Action Text";
            
                    
            public static readonly ID SubtitleFieldId = new ID("2fb9aebd-d6e1-4ea5-8a04-7b6ad0ec3132");
            public const string SubtitleFieldName = "Subtitle";
            
                    
            public static readonly ID TitleFieldId = new ID("aaeac7f2-e33e-4b34-9023-ab6f59d3a427");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Microsite_Home
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Microsite Home</para>
    /// <para>ID: 7139a8b6-68d9-471f-96e4-b87ed703c185</para>
    /// </summary>
    [SitecoreType(TemplateId=IMicrosite_HomeConstants.TemplateIdString)]
    public partial class Microsite_Home  : GlassBase, IMicrosite_Home 
    {
       
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 764646d1-347e-419d-8b86-67457c73d905</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Call to Action Link field.
                /// <para></para>
                /// <para>Field Type: Droptree</para>
                /// <para>Field ID: 918a64f3-3ce1-46fe-afe0-7bdeae9f6299</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.Call_To_Action_LinkFieldName)]
                public virtual Guid Call_To_Action_Link  {get; set;}
                    
                        /// <summary>
                /// The Call to Action Text field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 4b8cff92-abb0-4d0a-a396-cd2ad4b5a99b</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.Call_To_Action_TextFieldName)]
                public virtual string Call_To_Action_Text  {get; set;}
                    
                        /// <summary>
                /// The Subtitle field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 2fb9aebd-d6e1-4ea5-8a04-7b6ad0ec3132</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.SubtitleFieldName)]
                public virtual string Subtitle  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: aaeac7f2-e33e-4b34-9023-ab6f59d3a427</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_HomeConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore.Site_Sections
{


    /// <summary>
    /// IAudience_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Audience Section</para>
    /// <para>ID: 86cd0756-7b65-4cd5-865b-036f9f84498f</para>
    /// </summary>
    [SitecoreType(TemplateId=IAudience_SectionConstants.TemplateIdString)]
    public partial interface IAudience_Section : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ISite_Section
    {
                }


    public static partial class IAudience_SectionConstants{

            public const string TemplateIdString = "86cd0756-7b65-4cd5-865b-036f9f84498f";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Audience Section";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Audience_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Audience Section</para>
    /// <para>ID: 86cd0756-7b65-4cd5-865b-036f9f84498f</para>
    /// </summary>
    [SitecoreType(TemplateId=IAudience_SectionConstants.TemplateIdString)]
    public partial class Audience_Section  : GlassBase, IAudience_Section 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SectionConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SectionConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SectionConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SectionConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SectionConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// ITeam_Member Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Team Member</para>
    /// <para>ID: 97963d48-bd06-46ca-8279-cd2ba3c7aa36</para>
    /// </summary>
    [SitecoreType(TemplateId=ITeam_MemberConstants.TemplateIdString)]
    public partial interface ITeam_Member : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text, global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                                /// <summary>
                    /// The Job Title field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: d2e90283-29f2-4eaf-895e-e8de8daeec69</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITeam_MemberConstants.Job_TitleFieldName)]
                    string Job_Title  {get; set;}
            
                                /// <summary>
                    /// The Quote field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: f9b6ffef-1dc9-4c0e-a815-c62822e1cbdb</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITeam_MemberConstants.QuoteFieldName)]
                    string Quote  {get; set;}
            
                }


    public static partial class ITeam_MemberConstants{

            public const string TemplateIdString = "97963d48-bd06-46ca-8279-cd2ba3c7aa36";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Team Member";

                    
            public static readonly ID Job_TitleFieldId = new ID("d2e90283-29f2-4eaf-895e-e8de8daeec69");
            public const string Job_TitleFieldName = "Job Title";
            
                    
            public static readonly ID QuoteFieldId = new ID("f9b6ffef-1dc9-4c0e-a815-c62822e1cbdb");
            public const string QuoteFieldName = "Quote";
            
                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Team_Member
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Team Member</para>
    /// <para>ID: 97963d48-bd06-46ca-8279-cd2ba3c7aa36</para>
    /// </summary>
    [SitecoreType(TemplateId=ITeam_MemberConstants.TemplateIdString)]
    public partial class Team_Member  : GlassBase, ITeam_Member 
    {
       
                        /// <summary>
                /// The Job Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: d2e90283-29f2-4eaf-895e-e8de8daeec69</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.Job_TitleFieldName)]
                public virtual string Job_Title  {get; set;}
                    
                        /// <summary>
                /// The Quote field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: f9b6ffef-1dc9-4c0e-a815-c62822e1cbdb</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.QuoteFieldName)]
                public virtual string Quote  {get; set;}
                    
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITeam_MemberConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IAudience_Segment Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Audience Segment</para>
    /// <para>ID: b65cce04-bccb-4a58-b988-753d523c99a7</para>
    /// </summary>
    [SitecoreType(TemplateId=IAudience_SegmentConstants.TemplateIdString)]
    public partial interface IAudience_Segment : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text, global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                }


    public static partial class IAudience_SegmentConstants{

            public const string TemplateIdString = "b65cce04-bccb-4a58-b988-753d523c99a7";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Audience Segment";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Audience_Segment
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Audience Segment</para>
    /// <para>ID: b65cce04-bccb-4a58-b988-753d523c99a7</para>
    /// </summary>
    [SitecoreType(TemplateId=IAudience_SegmentConstants.TemplateIdString)]
    public partial class Audience_Segment  : GlassBase, IAudience_Segment 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SegmentConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SegmentConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SegmentConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SegmentConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IAudience_SegmentConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// ITerm Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Term</para>
    /// <para>ID: c6dd3cef-22af-4468-b3b0-82abfcde0f24</para>
    /// </summary>
    [SitecoreType(TemplateId=ITermConstants.TemplateIdString)]
    public partial interface ITerm : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                                /// <summary>
                    /// The Definition field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>
                    /// <para>Field ID: b636170c-2681-469a-a642-a6549c12d1e6</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITermConstants.DefinitionFieldName)]
                    string Definition  {get; set;}
            
                                /// <summary>
                    /// The Title field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: fbade872-82bd-45ad-a2ec-dadc723249da</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITermConstants.TitleFieldName)]
                    string Title  {get; set;}
            
                                /// <summary>
                    /// The Usage field.
                    /// <para></para>
                    /// <para>Field Type: Rich Text</para>
                    /// <para>Field ID: aa7ce48d-746c-42c7-bd64-9a51f7f10b7c</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ITermConstants.UsageFieldName)]
                    string Usage  {get; set;}
            
                }


    public static partial class ITermConstants{

            public const string TemplateIdString = "c6dd3cef-22af-4468-b3b0-82abfcde0f24";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Term";

                    
            public static readonly ID DefinitionFieldId = new ID("b636170c-2681-469a-a642-a6549c12d1e6");
            public const string DefinitionFieldName = "Definition";
            
                    
            public static readonly ID TitleFieldId = new ID("fbade872-82bd-45ad-a2ec-dadc723249da");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID UsageFieldId = new ID("aa7ce48d-746c-42c7-bd64-9a51f7f10b7c");
            public const string UsageFieldName = "Usage";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Term
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Term</para>
    /// <para>ID: c6dd3cef-22af-4468-b3b0-82abfcde0f24</para>
    /// </summary>
    [SitecoreType(TemplateId=ITermConstants.TemplateIdString)]
    public partial class Term  : GlassBase, ITerm 
    {
       
                        /// <summary>
                /// The Definition field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: b636170c-2681-469a-a642-a6549c12d1e6</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITermConstants.DefinitionFieldName)]
                public virtual string Definition  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: fbade872-82bd-45ad-a2ec-dadc723249da</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITermConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Usage field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: aa7ce48d-746c-42c7-bd64-9a51f7f10b7c</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITermConstants.UsageFieldName)]
                public virtual string Usage  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITermConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ITermConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// ISecurity_Page Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Security Page</para>
    /// <para>ID: d804da09-73f3-4bde-b9f7-86181aa7efa8</para>
    /// </summary>
    [SitecoreType(TemplateId=ISecurity_PageConstants.TemplateIdString)]
    public partial interface ISecurity_Page : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text, global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                }


    public static partial class ISecurity_PageConstants{

            public const string TemplateIdString = "d804da09-73f3-4bde-b9f7-86181aa7efa8";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Security Page";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Security_Page
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Security Page</para>
    /// <para>ID: d804da09-73f3-4bde-b9f7-86181aa7efa8</para>
    /// </summary>
    [SitecoreType(TemplateId=ISecurity_PageConstants.TemplateIdString)]
    public partial class Security_Page  : GlassBase, ISecurity_Page 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISecurity_PageConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISecurity_PageConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISecurity_PageConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISecurity_PageConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(ISecurity_PageConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IArticle Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Article</para>
    /// <para>ID: d9019e30-f954-46cc-aa70-3e928c40b5d0</para>
    /// </summary>
    [SitecoreType(TemplateId=IArticleConstants.TemplateIdString)]
    public partial interface IArticle : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text, global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                                /// <summary>
                    /// The Contributors field.
                    /// <para></para>
                    /// <para>Field Type: Checklist</para>
                    /// <para>Field ID: 82d725ed-6707-4532-86a6-5444e34332fd</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IArticleConstants.ContributorsFieldName)]
                    IEnumerable<Guid> Contributors  {get; set;}
            
                                /// <summary>
                    /// The Prerequisite Articles field.
                    /// <para></para>
                    /// <para>Field Type: Treelist</para>
                    /// <para>Field ID: efc4a071-5574-404a-8206-fb502fca909b</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IArticleConstants.Prerequisite_ArticlesFieldName)]
                    IEnumerable<Guid> Prerequisite_Articles  {get; set;}
            
                }


    public static partial class IArticleConstants{

            public const string TemplateIdString = "d9019e30-f954-46cc-aa70-3e928c40b5d0";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Article";

                    
            public static readonly ID ContributorsFieldId = new ID("82d725ed-6707-4532-86a6-5444e34332fd");
            public const string ContributorsFieldName = "Contributors";
            
                    
            public static readonly ID Prerequisite_ArticlesFieldId = new ID("efc4a071-5574-404a-8206-fb502fca909b");
            public const string Prerequisite_ArticlesFieldName = "Prerequisite Articles";
            
                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Article
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Article</para>
    /// <para>ID: d9019e30-f954-46cc-aa70-3e928c40b5d0</para>
    /// </summary>
    [SitecoreType(TemplateId=IArticleConstants.TemplateIdString)]
    public partial class Article  : GlassBase, IArticle 
    {
       
                        /// <summary>
                /// The Contributors field.
                /// <para></para>
                /// <para>Field Type: Checklist</para>
                /// <para>Field ID: 82d725ed-6707-4532-86a6-5444e34332fd</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.ContributorsFieldName)]
                public virtual IEnumerable<Guid> Contributors  {get; set;}
                    
                        /// <summary>
                /// The Prerequisite Articles field.
                /// <para></para>
                /// <para>Field Type: Treelist</para>
                /// <para>Field ID: efc4a071-5574-404a-8206-fb502fca909b</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.Prerequisite_ArticlesFieldName)]
                public virtual IEnumerable<Guid> Prerequisite_Articles  {get; set;}
                    
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IArticleConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore.Site_Sections
{


    /// <summary>
    /// IGlossary_Section Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Glossary Section</para>
    /// <para>ID: e35c9d40-8d28-4944-ab30-18e2789e6ba7</para>
    /// </summary>
    [SitecoreType(TemplateId=IGlossary_SectionConstants.TemplateIdString)]
    public partial interface IGlossary_Section : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ISite_Section
    {
                }


    public static partial class IGlossary_SectionConstants{

            public const string TemplateIdString = "e35c9d40-8d28-4944-ab30-18e2789e6ba7";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Glossary Section";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Glossary_Section
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Site Sections/Glossary Section</para>
    /// <para>ID: e35c9d40-8d28-4944-ab30-18e2789e6ba7</para>
    /// </summary>
    [SitecoreType(TemplateId=IGlossary_SectionConstants.TemplateIdString)]
    public partial class Glossary_Section  : GlassBase, IGlossary_Section 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGlossary_SectionConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGlossary_SectionConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGlossary_SectionConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGlossary_SectionConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGlossary_SectionConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IGeneral_Page Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/General Page</para>
    /// <para>ID: e6964c3e-d415-40c8-91d9-2bf90f6566e9</para>
    /// </summary>
    [SitecoreType(TemplateId=IGeneral_PageConstants.TemplateIdString)]
    public partial interface IGeneral_Page : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text
    {
                }


    public static partial class IGeneral_PageConstants{

            public const string TemplateIdString = "e6964c3e-d415-40c8-91d9-2bf90f6566e9";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "General Page";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
        
    }

    /// <summary>
    /// General_Page
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/General Page</para>
    /// <para>ID: e6964c3e-d415-40c8-91d9-2bf90f6566e9</para>
    /// </summary>
    [SitecoreType(TemplateId=IGeneral_PageConstants.TemplateIdString)]
    public partial class General_Page  : GlassBase, IGeneral_Page 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGeneral_PageConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGeneral_PageConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IGeneral_PageConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
            }
}
namespace LaunchContent.LaunchSitecore
{


    /// <summary>
    /// IMicrosite_Subpage Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Microsite Subpage</para>
    /// <para>ID: f52f00e0-3f65-4c1a-9bf6-af03ce94e599</para>
    /// </summary>
    [SitecoreType(TemplateId=IMicrosite_SubpageConstants.TemplateIdString)]
    public partial interface IMicrosite_Subpage : IGlassBase , global::LaunchContent.LaunchSitecore.Base_Templates.ITitle_Abstract_And_Text, global::LaunchContent.LaunchSitecore.Base_Templates.IGeneral_Fields
    {
                }


    public static partial class IMicrosite_SubpageConstants{

            public const string TemplateIdString = "f52f00e0-3f65-4c1a-9bf6-af03ce94e599";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "Microsite Subpage";

                    
            public static readonly ID AbstractFieldId = new ID("00e1d306-96bd-4b32-85b4-cd63c53cc6c1");
            public const string AbstractFieldName = "Abstract";
            
                    
            public static readonly ID BodyFieldId = new ID("5a5684bb-8b54-44f6-abcc-2bada05ada5d");
            public const string BodyFieldName = "Body";
            
                    
            public static readonly ID TitleFieldId = new ID("234542dc-c610-4ca8-baa6-2592a8bcb1d7");
            public const string TitleFieldName = "Title";
            
                    
            public static readonly ID IconFieldId = new ID("2b60d8c1-81db-45a7-b1cb-654cdda96ae3");
            public const string IconFieldName = "Icon";
            
                    
            public static readonly ID ImageFieldId = new ID("f9f7a706-72ce-4733-b930-9ff1d7b3efab");
            public const string ImageFieldName = "Image";
            
        
    }

    /// <summary>
    /// Microsite_Subpage
    /// <para></para>
    /// <para>Path: /sitecore/templates/Launch Sitecore/Microsite Subpage</para>
    /// <para>ID: f52f00e0-3f65-4c1a-9bf6-af03ce94e599</para>
    /// </summary>
    [SitecoreType(TemplateId=IMicrosite_SubpageConstants.TemplateIdString)]
    public partial class Microsite_Subpage  : GlassBase, IMicrosite_Subpage 
    {
       
                        /// <summary>
                /// The Abstract field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 00e1d306-96bd-4b32-85b4-cd63c53cc6c1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_SubpageConstants.AbstractFieldName)]
                public virtual string Abstract  {get; set;}
                    
                        /// <summary>
                /// The Body field.
                /// <para></para>
                /// <para>Field Type: Rich Text</para>
                /// <para>Field ID: 5a5684bb-8b54-44f6-abcc-2bada05ada5d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_SubpageConstants.BodyFieldName)]
                public virtual string Body  {get; set;}
                    
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 234542dc-c610-4ca8-baa6-2592a8bcb1d7</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_SubpageConstants.TitleFieldName)]
                public virtual string Title  {get; set;}
                    
                        /// <summary>
                /// The Icon field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 2b60d8c1-81db-45a7-b1cb-654cdda96ae3</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_SubpageConstants.IconFieldName)]
                public virtual Image Icon  {get; set;}
                    
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: f9f7a706-72ce-4733-b930-9ff1d7b3efab</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [SitecoreField(IMicrosite_SubpageConstants.ImageFieldName)]
                public virtual Image Image  {get; set;}
                    
            }
}
