# branches to build
branches:
  # whitelist
  only:
    - /release*/
    - develop
    - master

install:
  - choco install gitversion.portable -pre -y
  - nuget sources add -Name MyAccountFeed -Source https://ci.appveyor.com/nuget/seanholmesby-a4t5wrp1ias0 -UserName %nuget_user% -Password %nuget_password%

nuget:
  account_feed: false
  project_feed: false

#---------------------------------#
#       build configuration       #
#---------------------------------#

#branches:
#  only:
#    - master

image: Visual Studio 2017

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore Source\LaunchSitecoreMvc.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: msbuild Source\LaunchSitecoreMvc.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:normal /p:PackageVersion=%GitVersion_SemVer%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

  - path: Source\TDS.MVC.Master\bin\Package_$(configuration)\*.update
  - path: Source\LaunchSitecoreMvc\bin\Launch*

#---------------------------------#
#      deploy configuration    #
#---------------------------------#
deploy:
  description: 'LaunchSitecoreMvc'
  provider: GitHub
  auth_token:
    secure: msVKXtRiopd61F8PvlpMwvsh3UfnE1t4asmJTb8qp4BFJkqTCmwFrSXkKC2Amo09 # your encrypted token from GitHub
  artifact: /.*\.update/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only