---
ID: "b437187b-9b55-475a-b4da-35e34e3be410"
Parent: "bb5f90b5-6efc-4ff0-ba65-35d0c325afae"
Template: "bb5f90b5-6efc-4ff0-ba65-35d0c325afae"
Path: /sitecore/templates/Global/Content Templates/Quotation/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130817T092411
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "83ece5b6-e1fd-4442-a2f2-d5ac1a9b66e4"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130817T092411:635123282517658733"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
