---
ID: "b6ac9ca4-762c-41f8-a4c4-b3c1c2ec942a"
Parent: "c7e1c014-93c9-42d5-b4c8-a307ac30e929"
Template: "045377d9-c7b7-4c51-a1f8-722502885239"
Path: "/sitecore/content/Developing-in-Sitecore/Configuration"
DB: master
SharedFields:
- ID: "962a3491-463f-4e23-9a43-84a293473724"
  Hint: Visible Profiles
  Value: "{3CEA9A30-CFA9-42F4-BA09-9100BFB1FAC5}|{478859DC-EBE0-40A7-BD24-75D588FD3E09}"
- ID: "e31d4bcb-ac93-4376-ad09-1bea045c85a8"
  Hint: Title Comments
  Value: |
    You can use whatever string you want. The page title control will replace {0} with the name of the current item and the {1} with the name of the site section. If you would like to store page titles as a field, just edit the meta\title control to pull that field. The first string is used for the home page and the site sections pages. The second string is for lower pages such as articles and team member pages.
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 900
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "fe0fa952-c3ed-4966-9531-12f87cd023b6"
      Hint: Site Logo
      Value: |
        <image mediaid="{796F3B16-7547-4722-A155-128BD1E4EB84}" />
    - ID: "d7f0e179-3bc4-4eb3-b74e-8d4b5adbdeca"
      Hint: Layout Style
      Value: Full Width
    - ID: "f83dc33b-21ca-4c5e-8d19-8e4b7a204165"
      Hint: Header Color
      Value: "{EC721887-3C8C-427D-A815-30D52EB2AD10}"
    - ID: "0e248cc4-62f6-4f47-9ef5-b84d204cf4ba"
      Hint: Menu Color
      Value: "{3FF6A10E-9797-4797-A905-1DB655A7618C}"
    - ID: "d5230c73-cecf-484a-8c04-cead0e9fb005"
      Hint: Site Color
      Value: "{7B0BB706-F8B7-4AA3-9989-29563707B748}"
    - ID: "291c86a9-3dd9-400b-ad6b-756795f30379"
      Hint: Footer Color
      Value: "{3FF6A10E-9797-4797-A905-1DB655A7618C}"
    - ID: "6d2b2a4d-94cf-4008-8695-9010c79d05c0"
      Hint: Copyright Background Color
      Value: "{0122A0D6-10C6-42E1-AA9D-D79FB619B9C1}"
    - ID: "6a887010-7322-44b4-b05c-31697928b303"
      Hint: Page Title for Home and Site Sections
      Value: "{0} | Launch Sitecore"
    - ID: "436b14ee-7226-4831-ae7b-06ff5c8ff0d2"
      Hint: Page Title for Lower Pages
      Value: "{0} - {1} | Launch Sitecore"
    - ID: "b7066f9f-da7e-4ec4-95f4-d2b1e87c0caa"
      Hint: Copyright
      Value: "Copyright © 1999-2013 Sitecore"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20131115T221541
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ca0285c8-fc07-4185-96fd-31a8ef540a64"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20150715T151122Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
